name: anythingllm

networks:
  anything-llm:
    driver: bridge

services:
  anything-llm:
    container_name: anythingllm
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      # - "./.env:/app/server/.env"  # Coolify handles env vars differently
      - "../server/storage:/app/server/storage"
      - "../collector/hotdir/:/app/collector/hotdir"
      - "../collector/outputs/:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    # env_file:
    #   - .env  # Coolify handles env vars through its UI
    networks:
      - anything-llm
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mem0:
    image: ghcr.io/mem0-ai/mem0:latest
    environment:
      - MEM0_QDRANT_URL=http://qdrant:6333
      - MEM0_QDRANT_COLLECTION=mem0
      - MEM0_API_KEY=${MEM0_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    networks:
      - anything-llm

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    networks:
      - anything-llm

volumes:
  qdrant_storage:
