name: Deploy to DigitalOcean

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
          set -e
          cd /opt/anythingllm
          git fetch --all
          git reset --hard HEAD
          git pull
          cd docker
          docker compose down || true
          docker compose pull
          docker compose up -d
        EOF

    - name: Verify deployment
      run: |
        sleep 30
        curl -f http://${{ secrets.DROPLET_IP }}:3001 || exit 1
        echo "Deployment successful!"